[package]
name = "sudoku-rs"
version = "0.1.0"
authors = ["tomocafe <tomocafe@pm.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.11.0"
clap = "2.33.0"
lazy_static = "1.4.0"
